name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK using GitHub Action
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Reference secret for Project ID
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Reference secret for credentials

      # Step 3: Build Docker image for amd64 architecture
      - name: Build Docker image
        run: |
          docker build --platform=linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/smufti-web-frontend .

      # Step 4: Push Docker image to Google Container Registry (GCR)
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/smufti-web-frontend

      # Step 5: Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy smufti-web \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/smufti-web-frontend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account smufti-service-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
