name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  FRONTEND_SERVICE: frontend
  BACKEND_SERVICE: backend
  REGION: us-east1

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Deploy Backend
        run: |
          gcloud builds submit ./backend \
            --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}
          gcloud run deploy ${{ env.BACKEND_SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}"

      - name: Build and Deploy Frontend
        run: |
          gcloud builds submit ./frontend \
            --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }}
          gcloud run deploy ${{ env.FRONTEND_SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated

      - name: Show Output URLs
        run: |
          echo "Backend URL: $(gcloud run services describe ${{ env.BACKEND_SERVICE }} --platform managed --region ${{ env.REGION }} --format 'value(status.url)')"
          echo "Frontend URL: $(gcloud run services describe ${{ env.FRONTEND_SERVICE }} --platform managed --region ${{ env.REGION }} --format 'value(status.url)')"
